Repository Noostak/ScheTook-Android, pull requests merged in 2025-04, with the labels that each got.

#2 [Feature/#79] 캘린더 팝업 약속 조회 API 연결
  core/src/main/java/com/sopt/core/util/time/CalculateTimeFromLocalDate.kt
  core/src/main/java/com/sopt/core/util/time/CalculateTimeFromString.kt
  core/src/main/java/com/sopt/core/util/timetable/TimeTable.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetConfirmedDtoMapper.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetGroupConfirmedDetailDtoMapper.kt
  domain/src/main/java/com/sopt/domain/entity/AppointmentDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ConfirmedDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ScheduleDetailEntity.kt
  domain/src/main/java/com/sopt/domain/entity/ScheduleEntity.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentConfirm/AppointmentConfirmRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/screen/RecommendationScreen.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleDetailScreen.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleItem.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleListScreen.kt
  presentation/src/main/java/com/sopt/presentation/groupCreate/GroupCreateViewModel.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/confirmedDetail/ConfirmedDetailRoute.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ConfirmedScreen.kt
  presentation/src/main/java/com/sopt/presentation/groupDetail/screen/ProgressScreen.kt
Labels: ⭐ [FEAT], :four_leaf_clover: 언지

#4 [Feature/#3] : 캘린더 optionId, 시간 조회 duration 필드 추가
  data/src/main/java/com/sopt/data/dto/response/ResponseGetCalendarDto.kt
  data/src/main/java/com/sopt/data/dto/response/ResponseGetTimeTableDto.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetCalendarDtoMapper.kt
  data/src/main/java/com/sopt/data/mapper/ResponseGetTimeTableDtoMapper.kt
  domain/src/main/java/com/sopt/domain/entity/CalendarEntity.kt
  domain/src/main/java/com/sopt/domain/entity/TimeTableEntity.kt
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/AppointmentSideEffect.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentCheck/AppointmentCheckRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentCheck/AppointmentCheckViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointment/navigation/AppointmentNavigation.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreateInfo/AppointmentCreateInfoRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarRoute.kt
  presentation/src/main/java/com/sopt/presentation/calendar/CalendarViewModel.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleItem.kt
  presentation/src/main/java/com/sopt/presentation/calendar/component/bottomsheet/ScheduleListScreen.kt
Labels: ➕ [ADD], :fallen_leaf: 가을

#6 [Feature/#5] : 소요시간 이하 입력 방지
  core/src/main/java/com/sopt/core/designsystem/component/checkbox/NoostakCheckbox.kt
  core/src/main/java/com/sopt/core/designsystem/component/timetable/NoostakEditableTimeTable.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentCheck/AppointmentCheckRoute.kt
  presentation/src/main/java/com/sopt/presentation/appointment/appointmentCheck/AppointmentCheckViewModel.kt
  presentation/src/main/java/com/sopt/presentation/appointmentCreate/appointmentCreateTimePicker/AppointmentCreateTimePickerRoute.kt
  presentation/src/main/res/values/strings.xml
Labels: :fallen_leaf: 가을, ⭐ [FEAT]
